- LICENSE
- package.json
> LICENSEを作成

- .githooks/pre-commit
- .gitignore
- .prettierrc
- .vscode/extensions.json
- .vscode/settings.json
- commands/join.js
- commands/leave.js
- commands/purge.js
- commands/random.js
- commands/read.js
- commands/readtoggle.js
- commands/view.js
- commands/voice.js
- contentConverter.js
- deployGlobalCommand.js
- deployGuildCommand.js
- index.js
- package-lock.json
- package.json
- utils.js
- voiceRead.js
> Prettier 導入

- commands/join.js
- commands/leave.js
- commands/purge.js
- commands/random.js
- commands/readtoggle.js
- commands/view.js
- commands/voice.js
> ephemeral オプションを追加

- .github/ISSUE_TEMPLATE/0_bug_report.yml
- .github/ISSUE_TEMPLATE/1_improvement_suggestions.yml
- .github/ISSUE_TEMPLATE/2_feature_request.yml
> Issue フォーム作成

- commands/join.js
- commands/leave.js
- commands/purge.js
- commands/random.js
- commands/read.js
- commands/readtoggle.js
- commands/view.js
- commands/voice.js
- deployGlobalCommand.js
- deployGuildCommand.js
- package.json
- pnpm-lock.yaml
v14の仕様変更に合わせて、コードを修正。
参照: [Updating from v13 to v14
](https://discordjs.guide/additional-info/changes-in-v14.html)
> Minor update

- README.md
> ｱｯﾌﾟﾃﾞｰﾄﾑｫﾁREADMEｻｰﾊﾞｰ!

- package.json
- pnpm-lock.yaml
This reverts commit a4340bf0f2ea71810221c7277d61b281731bb365.
> Revert "fix(deps): update dependency axios to v1.2.0 (#242)"

- package.json
- pnpm-lock.yaml
- src/contentConverter.js
これでundefinedって読むのは大丈夫なはず
一部の絵文字の読み方がちょっと違うけどまぁいいよね？
> Fix some emoji is saying undefined

- src/contentConverter.js
Fixed a bug that caused custom emoji IDs to be read out.
> Fix custom emoji reading

- src/contentConverter.js
close #276 
アスタリスクが読み上げられる問題を修正しました。
> Fixed a asterisk to be read out bug

- package.json
- pnpm-lock.yaml
- src/contentConverter.js
close #329
close #327 
Co-authored-by: kazukazu123123 <kazukazu123123@users.noreply.github.com>
> Fix emoji shortcodes

- src/index.js
> Auto vc leave

- src/index.js
> 同じVCに入っている場合にのみ読み上げるように修正

- src/commands/leave.ts
> Fix leave command

- src/contentConverter.ts
close #341 
undefined になるクソカス仕様を修正
> Fix emoji convert

- src/index.ts
> feat: process.title を書き換える

- src/index.ts
> Fix signal handle

- src/contentConverter.ts
> Fix emoji convert (2)

- src/commands/join.ts
> fix: worker check

- package.json
Reverts kazukazu123123/pow#497
> Revert "Release v2.1.8"

- src/index.ts
> Fix restart message color

- .github/workflows/docker.yml
> Fix docker action

- src/commands/help.ts
> Fix help message

- src/commands/reset.ts
> Add reset command

- .github/workflows/versioning.yml
- .github/workflows/versioning/main.sh
Reverts kazukazu123123/pow#538
ダメでした
> Revert "Fix versioning action"

- src/commands/view.ts
> Update view command

- src/index.ts
> add makeCache option

- src/commands/join.ts
- src/index.ts
- src/joinMessage.ts
- src/worker.ts
> fix(worker): workerの準備が整う前にjoinできるのが修正できたかもしれない

- src/contentConverter.ts
> fix: url convert

- src/commands/read.ts
- src/contentConverter.ts
- src/events/messageCreate.ts
> feat: add read stickers feature

- package.json
> Override any environment variables that have already been set on your machine with values from your .env file.
https://github.com/motdotla/dotenv#override
> fix dev script

- src/commands/help.ts
> refactor: integrity 要らんくなったっぽい2

- Dockerfile
> chore(container): curl に `--compressed`オプションを追加

- src/commands/join.ts
- src/commands/leave.ts
- src/commands/purge.ts
- src/commands/read.ts
- src/commands/rejoin.ts
- src/commands/reset.ts
- src/commands/skip.ts
- src/commands/ttsmute.ts
- src/components/preCheck.ts
- src/connectionCtx.ts
- src/errors/ConnectionError.ts
- src/errors/FetchResponseError.ts
- src/errors/HandleInteractionError.ts
- src/errors/PowError.ts
- src/errors/WorkerError.ts
- src/errors/index.ts
- src/guildCtx.ts
- src/voiceRead.ts
> fix(refactor): エラー処理を修正

- package.json
- pnpm-lock.yaml
Reverts kazukazu123123/pow#741
assert が with に変換されるため。
> Revert "chore(deps): update dependency @swc/core to v1.3.81"

- .swcrc
- src/commands/help.ts
- src/index.ts
> refactor: use package.json without assert

- src/commands/read.ts
- src/connectionCtx.ts
> feat(commands): `/read` に声設定のオプションを追加

- src/guildCtx.ts
> fix(commands): join コマンドのエラー処理を修正

- src/db.ts
- src/listeners/voiceStateUpdate.ts
> feat: ユーザー設定をキャッシュするようにする

- src/commands/reset.ts
- src/guildCtx.ts
- src/listeners/guildMemberRemove.ts
> fix(commands): /reset コマンドで GuildContext をリセットするように修正

- src/commands/join.ts
- src/commands/rejoin.ts
- src/connectionCtx.ts
- src/db.ts
- src/guildCtx.ts
- src/index.ts
- src/joinMessage.ts
- src/load.ts
> feat: 再起動後に再参加する機能を追加

- .github/workflows/semver-label.yml
> ci: SemVer label ワークフローのトリガーを修正

- Dockerfile
Reverts kazukazu123123/pow#862
> Revert "chore: Dockerfile 改善"

- Dockerfile
なんか勧められたので。
https://docs.docker.com/engine/reference/builder/#copy---link
> chore: Dockerfile 改善

- eslint.config.mjs
- src/commands/leave.ts
- src/commands/read.ts
- src/commands/rejoin.ts
- src/commands/reset.ts
- src/commands/ttsmute.ts
- src/connectionCtx.ts
- src/db.ts
- src/guildCtx.ts
- src/index.ts
- src/listeners/channelUpdate.ts
- src/listeners/guildMemberRemove.ts
- src/listeners/messageCreate.ts
- src/listeners/voiceStateUpdate.ts
- src/utils.ts
Tested-by: kazukazu123123 <50506519+kazukazu123123@users.noreply.github.com>
> refactor: fix '@typescript-eslint/no-floating-promises' lint error

- package.json
- pnpm-lock.yaml
This reverts commit 1f5df5a67f2a348fcb18adc36684b8984f37c1fb.
> revert: "chore(deps): update dependency eslint to v9"

- src/contentConverter.ts
> feat: add parseTimestamp

- src/contentConverter.ts
ほんとにツリーハウスが崩壊したので直した
close #1242
> fix: update dateStyle to 'long' in contentConverter.ts

- src/contentConverter.ts
> feat: Add relativetime for timestamp

- .vscode/settings.json
Changed the ESLint config property from
`eslint.experimental.useFlatConfig` to `eslint.useFlatConfig`.
> chore: update ESLint config property name

- src/commands/userSettings.ts
- src/db.ts
- src/load.ts
- src/utils.ts
> fix: import from .prisma/client

- src/commands/userSettings.ts
- src/db.ts
- src/load.ts
- src/utils.ts
Reverts eoeo-org/pow#1405
botが動かなくなるのでダメ
> revert: "fix: import from .prisma/client"

- src/contentConverter.ts
Reverts eoeo-org/pow#1457
要らない
> revert: "feat: allow fallback to user name if guild member not found"

- package.json
- pnpm-lock.yaml
> revert: "chore(deps): update dependency @swc/core to v1.7.42"

- package.json
- pnpm-lock.yaml
https://github.com/discordjs/discord.js/commit/7397dfe49e203cc85c66514fc1341e8d7bdecb32#diff-68c2871252db162413e4b550fa52bf018a6553742ba26f91274b2b4f1273dc58R54
> deps: remove sodium-native

- Dockerfile
- package.json
- pnpm-lock.yaml
> [zlib-sync](https://www.npmjs.com/package/zlib-sync) for WebSocket data compression and inflation
https://github.com/discordjs/discord.js/blob/14.16.3/packages/discord.js/README.md#optional-packages
> deps: add zlib-sync

- package.json
- pnpm-lock.yaml
> [bufferutil](https://www.npmjs.com/package/bufferutil) for a much faster WebSocket connection
https://github.com/discordjs/discord.js/blob/14.16.3/packages/discord.js/README.md#optional-packages
> deps: add bufferutil

- package.json
- pnpm-lock.yaml
> revert: "deps: remove ffmpeg-static"

- .gitattributes
Reverts eoeo-org/pow#1555
要らない
> revert: "chore: exclude the husky directory from language statistics"

- package.json
- pnpm-lock.yaml
https://github.com/prettier/eslint-config-prettier/blob/v10.0.3/CHANGELOG.md#patch-changes
> chore(deps): remove unnecessary @types/eslint-config-prettier
